-- Table: Composers
CREATE TABLE Composers (
    composer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    full_name TEXT NOT NULL,
    era TEXT NOT NULL,
    nationality TEXT,
    main_instrument TEXT
);

-- Table: Emotions
CREATE TABLE Emotions (
    emotion_id INTEGER PRIMARY KEY AUTOINCREMENT,
    emotion_name TEXT NOT NULL
);

-- Table: Pieces
CREATE TABLE Pieces (
    piece_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    title TEXT,
    composer_id INTEGER NOT NULL,
    era TEXT NOT NULL,
    major_scale TEXT,
    difficulty INTEGER CHECK(difficulty BETWEEN 1 AND 10),
    emotion_id INTEGER,
    type TEXT,
    FOREIGN KEY (composer_id) REFERENCES Composers(composer_id),
    FOREIGN KEY (emotion_id) REFERENCES Emotions(emotion_id)
);

-- Insert Emotions
INSERT INTO Emotions (emotion_name) VALUES
('Tranquility'),
('Melancholy'),
('Tension'),
('Triumph'),
('Longing');

-- Insert Composers
INSERT INTO Composers (full_name, era, nationality, main_instrument) VALUES
('Johann Sebastian Bach', 'Baroque', 'German', 'Organ'),
('Wolfgang Amadeus Mozart', 'Classical', 'Austrian', 'Piano'),
('Ludwig van Beethoven', 'Classical/Romantic', 'German', 'Piano'),
('Frédéric Chopin', 'Romantic', 'Polish', 'Piano'),
('Franz Liszt', 'Romantic', 'Hungarian', 'Piano'),
('Sergei Rachmaninoff', 'Romantic/20th Century', 'Russian', 'Piano'),
('Claude Debussy', '20th Century/Impressionist', 'French', 'Piano'),
('Maurice Ravel', '20th Century/Impressionist', 'French', 'Piano'),
('Pyotr Ilyich Tchaikovsky', 'Romantic', 'Russian', 'Piano'),
('Robert Schumann', 'Romantic', 'German', 'Piano');

-- Insert 100 Pieces
INSERT INTO Pieces (name, title, composer_id, era, major_scale, difficulty, emotion_id, type) VALUES
('Piece 1', NULL, 1, 'Baroque', 'C minor', 10, 1, 'Fugue'),
('Piece 2', NULL, 2, 'Classical', 'G minor', 5, 3, 'Prelude'),
('Piece 3', 'Title 3', 10, 'Romantic', 'B♭ major', 9, 5, 'Prelude'),
('Piece 4', NULL, 6, 'Romantic/20th Century', 'E♭ major', 10, 4, 'Polonaise'),
('Piece 5', NULL, 3, 'Classical/Romantic', 'B♭ major', 7, 3, 'Ballade'),
('Piece 6', 'Title 6', 8, '20th Century/Impressionist', 'F major', 6, 5, 'Mazurka'),
('Piece 7', NULL, 3, 'Classical/Romantic', 'F minor', 8, 1, 'Impromptu'),
('Piece 8', NULL, 8, '20th Century/Impressionist', 'E♭ major', 7, 2, 'Waltz'),
('Piece 9', 'Title 9', 7, '20th Century/Impressionist', 'A major', 5, 2, 'Sonata'),
('Piece 10', NULL, 5, 'Romantic', 'A major', 6, 2, 'Prelude'),
('Piece 11', NULL, 10, 'Romantic', 'F minor', 8, 2, 'Polonaise'),
('Piece 12', 'Title 12', 8, '20th Century/Impressionist', 'F minor', 8, 4, 'Prelude'),
('Piece 13', NULL, 2, 'Classical', 'C major', 9, 4, 'Prelude'),
('Piece 14', NULL, 7, '20th Century/Impressionist', 'D major', 8, 4, 'Rhapsody'),
('Piece 15', 'Title 15', 4, 'Romantic', 'B minor', 7, 4, 'Sonata'),
('Piece 16', NULL, 5, 'Romantic', 'D major', 5, 2, 'Sonata'),
('Piece 17', NULL, 3, 'Classical/Romantic', 'D major', 9, 4, 'Nocturne'),
('Piece 18', 'Title 18', 3, 'Classical/Romantic', 'A major', 8, 1, 'Prelude'),
('Piece 19', NULL, 8, '20th Century/Impressionist', 'G minor', 9, 3, 'Mazurka'),
('Piece 20', NULL, 1, 'Baroque', 'D major', 5, 3, 'Fugue'),
('Piece 21', 'Title 21', 1, 'Baroque', 'B minor', 7, 4, 'Ballade'),
('Piece 22', NULL, 10, 'Romantic', 'B♭ major', 3, 3, 'Mazurka'),
('Piece 23', NULL, 6, 'Romantic/20th Century', 'D minor', 6, 1, 'Mazurka'),
('Piece 24', 'Title 24', 4, 'Romantic', 'E♭ major', 9, 2, 'Ballade'),
('Piece 25', NULL, 6, 'Romantic/20th Century', 'A major', 3, 4, 'Rhapsody'),
('Piece 26', NULL, 7, '20th Century/Impressionist', 'F major', 3, 5, 'Polonaise'),
('Piece 27', 'Title 27', 10, 'Romantic', 'D minor', 8, 5, 'Mazurka'),
('Piece 28', NULL, 6, 'Romantic/20th Century', 'D minor', 4, 2, 'Impromptu'),
('Piece 29', NULL, 6, 'Romantic/20th Century', 'G minor', 7, 3, 'Ballade'),
('Piece 30', 'Title 30', 6, 'Romantic/20th Century', 'F major', 10, 3, 'Symphony'),
('Piece 31', NULL, 6, 'Romantic/20th Century', 'B♭ major', 7, 2, 'Concerto'),
('Piece 32', NULL, 4, 'Romantic', 'G minor', 8, 1, 'Nocturne'),
('Piece 33', 'Title 33', 9, 'Romantic', 'G minor', 10, 5, 'Concerto'),
('Piece 34', NULL, 10, 'Romantic', 'G minor', 8, 5, 'Fugue'),
('Piece 35', NULL, 1, 'Baroque', 'G major', 8, 1, 'Ballade'),
('Piece 36', 'Title 36', 1, 'Baroque', 'B minor', 9, 4, 'Sonata'),
('Piece 37', NULL, 9, 'Romantic', 'A minor', 3, 2, 'Polonaise'),
('Piece 38', NULL, 8, '20th Century/Impressionist', 'D minor', 9, 5, 'Mazurka'),
('Piece 39', 'Title 39', 10, 'Romantic', 'A minor', 10, 1, 'Waltz'),
('Piece 40', NULL, 4, 'Romantic', 'A major', 4, 5, 'Waltz'),
('Piece 41', NULL, 6, 'Romantic/20th Century', 'E♭ major', 3, 5, 'Nocturne'),
('Piece 42', 'Title 42', 4, 'Romantic', 'E♭ major', 9, 1, 'Waltz'),
('Piece 43', NULL, 5, 'Romantic', 'C minor', 3, 1, 'Nocturne'),
('Piece 44', NULL, 10, 'Romantic', 'A major', 5, 1, 'Etude'),
('Piece 45', 'Title 45', 6, 'Romantic/20th Century', 'F major', 3, 4, 'Etude'),
('Piece 46', NULL, 2, 'Classical', 'G minor', 8, 1, 'Etude'),
('Piece 47', NULL, 8, '20th Century/Impressionist', 'D major', 7, 4, 'Sonata'),
('Piece 48', 'Title 48', 10, 'Romantic', 'D minor', 3, 5, 'Prelude'),
('Piece 49', NULL, 2, 'Classical', 'B♭ major', 4, 4, 'Concerto'),
('Piece 50', NULL, 10, 'Romantic', 'B minor', 4, 2, 'Prelude'),
('Piece 51', 'Title 51', 1, 'Baroque', 'F minor', 9, 3, 'Sonata'),
('Piece 52', NULL, 6, 'Romantic/20th Century', 'F minor', 10, 5, 'Symphony'),
('Piece 53', NULL, 3, 'Classical/Romantic', 'A minor', 5, 3, 'Ballade'),
('Piece 54', 'Title 54', 6, 'Romantic/20th Century', 'G major', 4, 3, 'Concerto'),
('Piece 55', NULL, 5, 'Romantic', 'G minor', 7, 4, 'Impromptu'),
('Piece 56', NULL, 1, 'Baroque', 'F major', 7, 1, 'Concerto'),
('Piece 57', 'Title 57', 8, '20th Century/Impressionist', 'E♭ major', 4, 2, 'Fugue'),
('Piece 58', NULL, 8, '20th Century/Impressionist', 'G minor', 6, 3, 'Prelude'),
('Piece 59', NULL, 7, '20th Century/Impressionist', 'B minor', 10, 1, 'Polonaise'),
('Piece 60', 'Title 60', 8, '20th Century/Impressionist', 'F major', 6, 2, 'Rhapsody'),
('Piece 61', NULL, 9, 'Romantic', 'G minor', 8, 4, 'Mazurka'),
('Piece 62', NULL, 7, '20th Century/Impressionist', 'D major', 3, 1, 'Waltz'),
('Piece 63', 'Title 63', 7, '20th Century/Impressionist', 'B♭ major', 4, 2, 'Impromptu'),
('Piece 64', NULL, 5, 'Romantic', 'B♭ major', 3, 4, 'Symphony'),
('Piece 65', NULL, 9, 'Romantic', 'G minor', 3, 4, 'Nocturne'),
('Piece 66', 'Title 66', 10, 'Romantic', 'C major', 6, 3, 'Symphony'),
('Piece 67', NULL, 9, 'Romantic', 'G minor', 6, 2, 'Waltz'),
('Piece 68', NULL, 5, 'Romantic', 'B♭ major', 4, 3, 'Prelude'),
('Piece 69', 'Title 69', 3, 'Classical/Romantic', 'F major', 6, 3, 'Mazurka'),
('Piece 70', NULL, 10, 'Romantic', 'E♭ major', 9, 1, 'Symphony'),
('Piece 71', NULL, 3, 'Classical/Romantic', 'D major', 3, 3, 'Concerto'),
('Piece 72', 'Title 72', 3, 'Classical/Romantic', 'E♭ major', 6, 4, 'Polonaise'),
('Piece 73', NULL, 1, 'Baroque', 'C minor', 3, 5, 'Fugue'),
('Piece 74', NULL, 7, '20th Century/Impressionist', 'D minor', 10, 4, 'Polonaise'),
('Piece 75', 'Title 75', 7, '20th Century/Impressionist', 'E♭ major', 8, 5, 'Polonaise'),
('Piece 76', NULL, 10, 'Romantic', 'A major', 9, 4, 'Nocturne'),
('Piece 77', NULL, 3, 'Classical/Romantic', 'G major', 3, 3, 'Mazurka'),
('Piece 78', 'Title 78', 10, 'Romantic', 'B minor', 6, 1, 'Sonata'),
('Piece 79', NULL, 3, 'Classical/Romantic', 'E♭ major', 5, 5, 'Etude'),
('Piece 80', NULL, 4, 'Romantic', 'F major', 8, 4, 'Nocturne'),
('Piece 81', 'Title 81', 3, 'Classical/Romantic', 'D major', 10, 1, 'Rhapsody'),
('Piece 82', NULL, 5, 'Romantic', 'F major', 6, 2, 'Fugue'),
('Piece 83', NULL, 6, 'Romantic/20th Century', 'E♭ major', 6, 2, 'Impromptu'),
('Piece 84', 'Title 84', 6, 'Romantic/20th Century', 'B minor', 5, 2, 'Mazurka'),
('Piece 85', NULL, 2, 'Classical', 'C major', 6, 5, 'Mazurka'),
('Piece 86', NULL, 5, 'Romantic', 'C minor', 6, 2, 'Symphony'),
('Piece 87', 'Title 87', 6, 'Romantic/20th Century', 'B♭ major', 5, 1, 'Etude'),
('Piece 88', NULL, 6, 'Romantic/20th Century', 'E♭ major', 5, 3, 'Nocturne'),
('Piece 89', NULL, 2, 'Classical', 'A minor', 4, 3, 'Symphony'),
('Piece 90', 'Title 90', 3, 'Classical/Romantic', 'E♭ major', 7, 1, 'Symphony'),
('Piece 91', NULL, 10, 'Romantic', 'C minor', 5, 5, 'Mazurka'),
('Piece 92', NULL, 2, 'Classical', 'F minor', 5, 4, 'Etude'),
('Piece 93', 'Title 93', 4, 'Romantic', 'F major', 3, 5, 'Symphony'),
('Piece 94', NULL, 2, 'Classical', 'E♭ major', 5, 2, 'Etude'),
('Piece 95', NULL, 5, 'Romantic', 'C major', 9, 1, 'Etude'),
('Piece 96', 'Title 96', 9, 'Romantic', 'B minor', 4, 4, 'Symphony'),
('Piece 97', NULL, 6, 'Romantic/20th Century', 'F minor', 3, 3, 'Mazurka'),
('Piece 98', NULL, 8, '20th Century/Impressionist', 'F minor', 9, 5, 'Etude'),
('Piece 99', 'Title 99', 5, 'Romantic', 'D minor', 6, 4, 'Impromptu'),
('Piece 100', NULL, 2, 'Classical', 'F minor', 3, 3, 'Etude');
