import random

quote1 = "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill"
quote2 = "The only way to do great work is to love what you do. – Steve Jobs"
quote3 = "Believe you can and you’re halfway there. – Theodore Roosevelt"
quote4 = "Start where you are. Use what you have. Do what you can. – Arthur Ashe"
quote5 = "You miss 100% of the shots you don’t take. – Wayne Gretzky"
quote6 = "Do not wait to strike till the iron is hot; but make it hot by striking. – William Butler Yeats"
quote7 = "Everything you’ve ever wanted is on the other side of fear. – George Addair"
quote8 = "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis"
quote9 = "Dream big and dare to fail. – Norman Vaughan"
quote10 = "It does not matter how slowly you go as long as you do not stop. – Confucius"
quote11 = "Action is the foundational key to all success. – Pablo Picasso"
quote12 = "Don’t watch the clock; do what it does. Keep going. – Sam Levenson"
quote13 = "Perseverance is not a long race; it’s many short races one after the other. – Walter Elliot"
quote14 = "The best way out is always through. – Robert Frost"
quote15 = "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman"
quote16 = "What you do today can improve all your tomorrows. – Ralph Marston"
quote17 = "Doubt kills more dreams than failure ever will. – Suzy Kassem"
quote18 = "Strive not to be a success, but rather to be of value. – Albert Einstein"
quote19 = "The harder you work for something, the greater you’ll feel when you achieve it."
quote20 = "Great things never came from comfort zones."
quote21 = "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller"
quote22 = "Push yourself, because no one else is going to do it for you."
quote23 = "Success doesn’t just find you. You have to go out and get it."
quote24 = "Opportunities don’t happen. You create them. – Chris Grosser"
quote25 = "It always seems impossible until it’s done. – Nelson Mandela"
quote26 = "You are capable of more than you know."
quote27 = "If you want to lift yourself up, lift up someone else. – Booker T. Washington"
quote28 = "Don’t limit your challenges. Challenge your limits."
quote29 = "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt"
quote30 = "Mistakes are proof that you are trying."
quote31 = "Stay away from those people who try to disparage your ambitions. – Mark Twain"
quote32 = "The secret of getting ahead is getting started. – Mark Twain"
quote33 = "Aim for the moon. If you miss, you may hit a star. – W. Clement Stone"
quote34 = "Every moment is a fresh beginning. – T.S. Eliot"
quote35 = "Make each day your masterpiece. – John Wooden"
quote36 = "You don’t have to be perfect to be amazing."
quote37 = "Be stubborn about your goals and flexible about your methods."
quote38 = "It’s never too late to be what you might have been. – George Eliot"
quote39 = "Fall seven times, stand up eight. – Japanese Proverb"
quote40 = "Work hard in silence, let success make the noise."
quote41 = "Nothing will work unless you do. – Maya Angelou"
quote42 = "Energy and persistence conquer all things. – Benjamin Franklin"
quote43 = "If you can dream it, you can do it. – Walt Disney"
quote44 = "One day or day one. You decide."
quote45 = "You don’t have to see the whole staircase, just take the first step. – Martin Luther King Jr."
quote46 = "Difficult roads often lead to beautiful destinations."
quote47 = "Do something today that your future self will thank you for."
quote48 = "The best way to predict the future is to create it. – Peter Drucker"
quote49 = "If you get tired, learn to rest, not to quit. – Banksy"
quote50 = "Small deeds done are better than great deeds planned. – Peter Marshall"
quote51 = "You are stronger than you think."
quote52 = "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill"
quote53 = "If you’re going through hell, keep going. – Winston Churchill"
quote54 = "Let your courage be bigger than your fears."
quote55 = "Don’t count the days, make the days count. – Muhammad Ali"
quote56 = "Life is 10% what happens to us and 90% how we react to it. – Charles Swindoll"
quote57 = "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson"
quote58 = "Be so good they can’t ignore you. – Steve Martin"
quote59 = "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi"
quote60 = "Wherever you go, go with all your heart. – Confucius"
quote61 = "Your only limit is your mind."
quote62 = "Focus on the step in front of you, not the whole staircase."
quote63 = "Today is your opportunity to build the tomorrow you want."
quote64 = "If you’re not willing to risk the usual, you’ll have to settle for the ordinary. – Jim Rohn"
quote65 = "There is no elevator to success. You have to take the stairs."
quote66 = "Don’t stop until you’re proud."
quote67 = "Winners are not afraid of losing. But losers are. Failure is part of the process of success. – Robert Kiyosaki"
quote68 = "Turn your wounds into wisdom. – Oprah Winfrey"
quote69 = "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett"
quote70 = "Don’t let yesterday take up too much of today. – Will Rogers"
quote71 = "All progress takes place outside the comfort zone. – Michael John Bobak"
quote72 = "Be yourself; everyone else is already taken. – Oscar Wilde"
quote73 = "It always seems too early until it’s too late."
quote74 = "You are not a drop in the ocean. You are the entire ocean in a drop. – Rumi"
quote75 = "Act as if what you do makes a difference. It does. – William James"
quote76 = "Just keep going. Everybody gets better if they keep at it. – Ted Williams"
quote77 = "One small positive thought can change your whole day."
quote78 = "Don’t be afraid to start over. It’s a chance to build something better."
quote79 = "Be the change that you wish to see in the world. – Mahatma Gandhi"
quote80 = "Sometimes we’re tested not to show our weaknesses, but to discover our strengths."
quote81 = "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson"
quote82 = "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway. – Earl Nightingale"
quote83 = "You are never too old to set another goal or to dream a new dream. – C.S. Lewis"
quote84 = "The biggest adventure you can take is to live the life of your dreams. – Oprah Winfrey"
quote85 = "Stay positive. Better days are on their way."
quote86 = "You’ve got this."
quote87 = "Keep your head up. Your heart will catch up."
quote88 = "If you can’t fly, then run. If you can’t run, then walk. If you can’t walk, then crawl. But whatever you do, you have to keep moving forward. – Martin Luther King Jr."
quote89 = "Stars can’t shine without darkness."
quote90 = "Remember why you started."
quote91 = "Take the risk or lose the chance."
quote92 = "Success is not for the chosen few, but for the few who choose it."
quote93 = "Your potential is endless."
quote94 = "Progress, not perfection."
quote95 = "The only thing standing between you and your goal is the story you keep telling yourself."
quote96 = "When you feel like quitting, think about why you started."
quote97 = "You only fail when you stop trying."
quote98 = "Sometimes the bravest thing you can do is just keep going."
quote99 = "Keep going. Everything you need will come to you at the perfect time."
quote100 = "You are enough. Always have been. Always will be."	

quotes = [quote1, quote2, quote3, quote4, quote5, quote6, quote7, quote8, quote9, quote10,
          quote11, quote12, quote13, quote14, quote15, quote16, quote17, quote18, quote19, quote20,
          quote21, quote22, quote23, quote24, quote25, quote26, quote27, quote28, quote29, quote30,
          quote31, quote32, quote33, quote34, quote35, quote36, quote37, quote38, quote39, quote40,
          quote41, quote42, quote43, quote44, quote45, quote46, quote47, quote48, quote49, quote50,
          quote51, quote52, quote53, quote54, quote55, quote56, quote57, quote58, quote59, quote60,
          quote61, quote62, quote63, quote64, quote65, quote66, quote67, quote68, quote69, quote70,
          quote71, quote72, quote73, quote74, quote75, quote76, quote77, quote78, quote79, quote80,
          quote81, quote82, quote83, quote84, quote85, quote86, quote87, quote88, quote89, quote90,
          quote91, quote92, quote93, quote94, quote95, quote96, quote97, quote98, quote99, quote100]

x = input("Are you interested in hearing a quote? [y/n] ")
if x.lower() in ['y', 'yes']:
    print(random.choice(quotes))
else:
    print("No quote for you today! Have a good one.")